- README.md
- tests/integration/new_relations/helpers.py
Some updates on README to list the features of the operator and some other details like security concerns and licensing.
It was based in the description made in the [MongoDB operator repository](https://github.com/canonical/mongodb-operator/blob/main/README.md).
> Readme updates

- README.md
since requires is deprecated updated the doc
> DOCS: update libs

- lib/charms/rolling_ops/v0/rollingops.py
- lib/charms/tls_certificates_interface/v1/tls_certificates.py
- src/relations/db.py
Copying over changes from the VM charm to keep the logic in sync
* Copying over changes from the VM charm to keep the logic in sync
*  Updating tls_certificates lib to latest fetched by charmcraft
* Check libs still complains, possibly due to differences in rollingops lib
* Updating tls_certificates lib
* Tweaking clearing of blocked status over relation extensions
> Update clear extensions blocked status to match VM charm

- .github/workflows/ci.yaml
- .github/workflows/release.yaml
- lib/charms/data_platform_libs/v0/data_interfaces.py
* Old version fails to publish libs
* Updated charming actions and data interface lib
> Charming actions version bump

- documentation/reference/charm.md
- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/ha_tests/application-charm/lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/new_relations/application-charm/lib/charms/data_platform_libs/v0/data_interfaces.py
- tox.ini
Very limited amount of files were being checked through `codespell`
Expand the amount of files checked by codespell
> Expand the amount of files checked by codespell

- README.md
The README file was a bit outdated and redundant to recently posted Tutorial on Discourse.
Updating README file to follow the common format for all SQL charms.
> Update README to follow the common style for all SQL charms

- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/loki_k8s/v0/loki_push_api.py
- lib/charms/observability_libs/v0/juju_topology.py
- lib/charms/postgresql_k8s/v0/postgresql.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- metadata.yaml
- src/charm.py
- src/constants.py
- src/grafana_dashboards/postgresql-metrics.json
- templates/patroni.yml.j2
- tests/integration/test_charm.py
- tests/unit/test_charm.py
PG-k8s missing COS support as per 
Added COS support to PG-k8s
> [DPE-1777] Feature/cos support

- metadata.yaml
* Missing zoneinfo
* Switches to rock with zoneinfo included
fixes #175
> [DPE-2015][DPE-2044] Add missing zoneinfo to Rock

- metadata.yaml
Security scan report:
```
Revision r60 (amd64; channels: 14/edge)
* python3-requests: 6155-1
```
Rebuild and update rock
> Update Rock due to outdated packages

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
> [MISC] Update charm libs

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/data_platform_libs/v0/s3.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- metadata.yaml
Switch to PPA postgresql prometheus exporter
> [DPE-2259] Use PPA postgresql exporter

- src/charm.py
Trying to get juju3 secrets fails randomly with:
```
getting cluster client: unable to determine legacy status for namespace "test-tls-w09r": namespaces "test-tls-w09r" is forbidden: User "system:serviceaccount:test-tls-w09r:unit-postgresql-k8s-1" cannot get resource "namespaces" in API group "" in the namespace "test-tls-w09r"
```
Retry getting the secrets to temporary stabilise things.
> [MISC] Retry getting secrets from juju3

- src/charm.py
Cross model relation between COS Prometheus and Postgresql can't resolve the provided Patroni endpoint and it will not register new nodes.
Switch to wildcard configuration.
> [DPE-2504] fully routable patroni cos

- src/constants.py
- templates/patroni.yml.j2
- tests/integration/test_tls.py
No log rotation rules for Postgresql logs.
Add log rotation rules from the spec.
> [DPE-1755] Log rotation

- docs/tutorial/t-enable-security.md
#267 
Updates headers to clarify secions.
> Clarify headers on security tutorial

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/data_platform_libs/v0/upgrade.py
- lib/charms/postgresql_k8s/v0/postgresql.py
- metadata.yaml
- tests/integration/test_db.py
Update rock to include snap changes (add locales)
> [MISC] Rock with locales

- .github/workflows/cla-check.yml
Check if Canonical's Contributor License Agreement has been signed by the PR author(s).
> add CLA check

- lib/charms/data_platform_libs/v0/data_interfaces.py
- tests/integration/new_relations/test_new_relations.py
Indico switched to multiple redis interfaces
* Switch the redis interfaces
* Bump libs
> [DPE-2844] Use named redis interfaces for indico

- config.yaml
- src/charm.py
- src/config.py
- tests/integration/test_plugins.py
> add spi extension

- metadata.yaml
- src/patroni.py
Updates from PPAs:
Patroni 3.1.2
Pgbackrest 2.48
> [DPE-3039] Update rock

- metadata.yaml
- src/charm.py
- src/patroni.py
* Update to latest Rock (14.10 and plugins)
* Update Patroni configuration in `update_config()` in one go
Outdated packages:
```
Revision r93 (amd64; channels: 14/edge)
* locales: 6541-2
* locales-all: 6541-2
```
> [DPE-3217] Update Rock to 14.10

- config.yaml
- lib/charms/postgresql_k8s/v0/postgresql.py
- metadata.yaml
- src/charm.py
- src/config.py
- tests/integration/test_plugins.py
Added support for new extensions/plugins:
- icu_ext
- address_standardizer
- address_standardizer
- address_standardizer_data_us
- bool_plperl
- hll
- hstore
- hypopg
- ip4r
- jsonb_plperl
- orafce
- pg_similarity
- pg_trgm
- plperl
- pltcl
- postgis
- postgis_raster
- postgis_tiger_geocoder
- postgis_topology
- prefix
- rdkit
- tds_fdw
- unaccent
> [DPE-1086] Add new extensions/plugins

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/loki_k8s/v0/loki_push_api.py
- lib/charms/rolling_ops/v0/rollingops.py
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- metadata.yaml
- tests/unit/test_charm.py
Outdated packages:
````
Revision r96 (amd64; channels: 14/edge)
* libldap-2.5-0: 6616-1
* libmysqlclient21: 6615-1
````
> [MISC] Update rock due to outdated packages

- lib/charms/data_platform_libs/v0/data_interfaces.py
- src/relations/db.py
- tests/integration/test_db.py
Port of https://github.com/canonical/postgresql-operator/pull/302
Block if a legacy relation requests roles.
> [DPE-3099] Block on legacy roles request

- lib/charms/loki_k8s/v0/loki_push_api.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- lib/charms/rolling_ops/v0/rollingops.py
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- src/charm.py
- tests/integration/helpers.py
- tests/integration/test_backups.py
Follow up to https://github.com/canonical/postgresql-k8s-operator/pull/461
Integration test for regeneration of pgbackrest config
> [DPE-2671] integration test

- config.yaml
- metadata.yaml
- src/config.py
- templates/patroni.yml.j2
- tests/integration/test_plugins.py
Added `timescaledb` plugin, as for VM [PR](https://github.com/canonical/postgresql-operator/pull/470)
> Added `timescaledb` plugin/extension

- LICENSE
This reverts commit d3f750b9de4df9f5ab72a66432349f6b0db4dbf0.
> [DPE-4423] Revert "update LICENSE file (#485)"

- .github/codecov.yml
- .github/workflows/ci.yaml
- .gitignore
- tests/unit/test_backups.py
- tests/unit/test_charm.py
- tests/unit/test_db.py
- tests/unit/test_patroni.py
- tests/unit/test_postgresql.py
- tests/unit/test_postgresql_provider.py
- tests/unit/test_postgresql_tls.py
- tests/unit/test_upgrade.py
- tests/unit/test_utils.py
- tox.ini
Upload coverage metrics to codecov
> [MISC] Add codecov

- tests/integration/new_relations/test_relations_coherence.py
Added test for relations coherence, as for VM [PR](https://github.com/canonical/postgresql-operator/pull/450)
> Added test for relations coherence

- tests/integration/ha_tests/helpers.py
- tests/integration/ha_tests/test_async_replication.py
- tests/integration/ha_tests/test_self_healing.py
See discussion in https://chat.canonical.com/canonical/pl/qxmty8wu87ga8f3qotnnqqemzy
> Quick fix for blocked CI

- .github/renovate.json5
- .github/workflows/ci.yaml
- lib/charms/data_platform_libs/v0/upgrade.py
- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/loki_k8s/v0/loki_push_api.py
- lib/charms/tempo_k8s/v1/charm_tracing.py
- lib/charms/tempo_k8s/v2/tracing.py
* Use reusable presets for Juju version pins
* Libs bump (except for k8s service patch)
> [MISC] Switch to resusable presets

- lib/charms/postgresql_k8s/v0/postgresql.py
- tests/unit/test_postgresql.py
The `lib/charms/postgresql_k8s/v0/postgresql.py` library got an update through https://github.com/canonical/postgresql-operator/pull/391, but that update hasn't been committed to this repo (which owns this library) yet.
Update the library.
> [DPE-4821] Update postgresql lib

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/data_platform_libs/v0/upgrade.py
- metadata.yaml
* Update rock (Postgresql 14.12)
* Update charm libs (without `kubernetes_service_patch`)
> [MISC] Update rock to 14.12

- src/backups.py
Port of https://github.com/canonical/postgresql-operator/pull/551
> [MISC] Fix: Show start/end time in UTC time in list-backups output

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/tempo_k8s/v1/charm_tracing.py
- lib/charms/tempo_k8s/v2/tracing.py
- pyproject.toml
- src/patroni.py
- src/relations/postgresql_provider.py
- tests/unit/test_patroni.py
* Increase the coverage so that codecov stops complaining
* Update libs (except `kubernetes_service_patch`)
> [MISC] Bump coverage

- src/backups.py
- tests/unit/test_backups.py
Follower tries to write to app peer data during stanza check
> [DPE-5325] Only write app data if leader

- lib/charms/loki_k8s/v1/loki_push_api.py
- lib/charms/tempo_k8s/v2/tracing.py
- src/charm.py
* Re-enable pebble log forwarding
* Update libs
> [MISC] Re-enable log forwarding

- src/charm.py
We still need to find a way to forward all the logs using the new approach.
Rollback to the old approach while we're still discussing how to solve this. This PR enables us to release a new stable revision.
> [DPE-5846] Temporarily disable log forwarding

- src/prometheus_alert_rules/postgresql_rules.yaml
#800 
Port of https://github.com/canonical/postgresql-operator/pull/724
> [DPE-6171] Fix typos in PG alert rules

- lib/charms/loki_k8s/v1/loki_push_api.py
- lib/charms/tempo_coordinator_k8s/v0/tracing.py
- tests/integration/test_storage.py
* Disable the storage test on arm
* Update libraries
> [MISC] Disable storage test on arm

- src/charm.py
- src/patroni.py
- tests/unit/test_charm.py
- tests/unit/test_patroni.py
Copy the degraded status message to primary from VM.
> [MISC] Add degraded status to primary message

- .github/renovate.json5
- .github/workflows/check_pr.yaml
- tests/integration/ha_tests/test_smoke.py
- tests/integration/ha_tests/test_upgrade_from_stable.py
- tests/integration/new_relations/test_new_relations_1.py
- tests/integration/test_backups_aws.py
- tests/integration/test_backups_gcp.py
- tests/integration/test_backups_pitr_aws.py
- tests/integration/test_backups_pitr_gcp.py
- tests/integration/test_plugins.py
- tests/integration/test_tls.py
- tests/spread/test_smoke.py/task.yaml
- tests/spread/test_upgrade_from_stable.py/task.yaml
Port back fixes and configs from `16/edge`.
> [DPE-6112] Dual branch config and test tweaks

- lib/charms/data_platform_libs/v0/data_interfaces.py
- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/postgresql_k8s/v0/postgresql.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- tests/unit/test_postgresql.py
* Disable pgaudit during plugin initialisation
* Update charm libraries
Port of https://github.com/canonical/postgresql-k8s-operator/pull/923 for PG k8s 14
> [DPE-6815] disable pgaudit during extensions change

- actions.yaml
Make scope mandatory for promote to primary action
> [MISC] Mandatory scope in promote action

- .github/workflows/release.yaml
Release flow was moved.
Move to the new flow and hope that it works.
> [MISC] Try to fix release

- .github/renovate.json5
Looks like the team got renamed
> [MISC] Renovate team

- tests/integration/new_relations/test_new_relations_1.py
- tests/integration/new_relations/test_relations_coherence.py
Fix due to stable release of 24.04 data-integrator
> [MISC] Fix data integrator tests

- src/charm.py
The logical replication PR (`16/edge` branch) changed the `relation_user_databases_map` property.
Port the changes to `14/edge` (`main` branch).
> [DPE-7870] Reorder map logic

- lib/charms/postgresql_k8s/v0/postgresql.py
- poetry.lock
- pyproject.toml
- src/authorisation_rules_observer.py
- src/backups.py
- src/charm.py
- src/ldap.py
- src/patroni.py
- src/relations/async_replication.py
- src/relations/logical_replication.py
- src/relations/postgresql_provider.py
- src/upgrade.py
- tests/unit/test_backups.py
- tests/unit/test_charm.py
- tox.ini
Enable pyright linting and fix some of the violations.
> [DPE-7963] Pyright
