.gitignore, CONTRIBUTING.md, README.md, actions.yaml, charmcraft.yaml, metadata.yaml, requirements.txt, src/charm.py, src/patroni.py, src/resources.yaml, templates/patroni.yml.j2, templates/postgresql.conf.j2, tests/data/patroni.yml, tests/data/postgresql.conf, tests/helpers.py, tests/integration/test_charm.py, tests/unit/helpers.py, tests/unit/test_charm.py, tests/unit/test_patroni.py, tox.ini
This PR enables the replication of the data among PostgreSQL units and also automatic failover, both features using [Patroni](https://github.com/zalando/patroni).
The integration tests focus on checking what is needed (configuration files and labels) to make Patroni manage correctly the replication and the automatic failover.
There is also a workaround in the update status hook to restart Patroni + PostgreSQL during an automatic failover. It’s needed because there is an issue about [zombie processes](https://github.com/canonical/pebble/issues/6).
Even separating some manual actions (manual failover and switchover) from this PR it got a little bigger. I’ll work to have smaller PRs in the future.
One last detail: the integration tests should fail as the docker image is not published yet, …
=> DPE-8 postgresql k8s replication with automatic failover

CONTRIBUTING.md, src/charm.py, tests/integration/test_charm.py, tox.ini
This PR adds some integration tests that verify that data persists in the postgres charm after graceful restarts and catastrophic failures.
- Integration tests are failing on GitHub because the test runner doesn't have access to the patroni container.
- Extra documentation for setup steps
- some minor cleanup for other tests, including `get_postgres_password` and `db_connect` methods
- Some extra `wait_for_idle`s in other tests to guarantee stability
- `test_persist_data_through_graceful_restart` test, which tests that data written to the primary persists across the other nodes after scaling juju down to 0 and back up to 3 nodes
- `test_persist_data_through_failure` test, which tests that data written to the primary persists across the other nodes after killing the primary using microk8s …
=> DPE-124 Additional Integration Testing 

.github/workflows/ci.yaml, tox.ini
In short this PR address JIRA ticket [DPE-212](https://warthogs.atlassian.net/browse/DPE-212).
In long:
* Currently, we don't have ROCKS available to publish our OCI images.
* This charm needs a custom OCI image from https://github.com/canonical/postgresql-patroni-container.
* In order to make the integration tests work we need to be able to pull the OCI image even if we still don't have it published to ROCKS.
* Pull, build and import the OCI image to microk8s registry during integration tests.
* There is an additional workaround for https://github.com/charmed-kubernetes/pytest-operator/issues/72.
* I'm not using something on python code as this implementation is a temporary workaround until ROCKS is available.
* It's possible to check the tests passing just on GitHub CI.
* Add OCI image …
=> DPE-212 Add build of OCI image for integration tests

tox.ini
Today `pytest-asyncio` was updated and changed the default asyncio mode to `strict`. This breaks some fixtures that we have in our charms, specially the ones used in the new relations tests.
[Release notes about the update](https://github.com/pytest-dev/pytest-asyncio/releases/tag/v0.19.0).
* Change the default asyncio mode to `auto` (the recommended if we do not use multiple async frameworks).
* Change default asyncio mode to auto.
=> Change default asyncio mode to fix error on fixtures

src/charm.py, tests/integration/test_charm.py
An error happens in the peer relation departed event if the application is removed from the model.
In the relation departed event handler, it is not being checked if the departed unit is the one that is receiving the event, so if the workload is gone an error happens when the handler tries to connect to the Patroni API (it is part of the process to update the list of the members of the Patroni cluster).
* Avoid handling the relation departed event in the departing unit.
* Some additional changes were made in `charm.py`, not related to the issue that was described. They are related to change the debug level of some logging calls that should be DEBUG instead of INFO, and also a missing comment about an error code. They were added as both changes and the solution for the issue are small.
* …
=> Avoid handling departing event in the departing unit

.github/workflows/ci.yaml, metadata.yaml, src/charm.py, src/constants.py, tests/integration/new_relations/application-charm/metadata.yaml, tests/integration/test_charm.py, tests/unit/test_charm.py, tox.ini
Relation interface name must not include hyphens.
Change `-` to `_` in the relation interface names.
* Fixed `postgresql-replicas` relation, which has the incorrect name and also the interface name in the wrong format.
* Also removed the duplicate CI run on `ci.yaml` when the code is merged to main. This was done because there is already a workflow running through `release.yaml`.
* Also fixed the juju python library in `tox.ini`. The dependecy was pointing to git instead of the published version, which caused some issues in the integration tests because of some breaking changes (one of them, related to https://github.com/juju/python-libjuju/commit/d42f7e6d6095c0ff7ed807764779b395092e2f7e, was fixed now on `tests/integration/test_charm.py` to avoid errors again when a new version of the …
=> Rename relation interface names

.github/workflows/release.yaml, tox.ini
Update Charmhub action to 2.0.0-rc to avoid creating revisions named `revundefined`.
* Changed flake version because the new version is not compatible with the plugin that is used in the CI.
=> Update Charmhub action

actions.yaml, src/charm.py, src/constants.py, tests/integration/helpers.py, tests/integration/test_charm.py, tests/unit/test_charm.py
* Database charms need a database user with a name that is easy to identify. This user shouldnt be used by charms related to the database charm.
* Change the default `postgres` superuser to a user called `operator`.
* Changed the `postgres` superuser to `operator`. Patroni uses that for some operations too.
* Patroni uses another user for replication, so no issues because of changing the superuser. 
* Unit and integration tests were updated.
* Manually tested the charm to check that the right user is created inside PostgreSQL.
* Change charm user to a user called `operator`.
=> Change charm database user

src/charm.py, src/constants.py, tests/unit/test_charm.py
* Secrets like passwords and TLS certificates should be moved to Juju secrets in the future.
* Currently, passwords are being set and retrieved from app relation data in multiple places, what can lead to a big refactor later (even more when we add TLS certificates to the charm).
* Move secret implementation logic to specific functions that can be easily refactored in the future to use Juju secrets instead of app relation data.
* Unit peer relation property was also added for future use cases.
* Some constants were created to avoid the same strings in multiple places.
* Additional unit tests were added.
* Tested using integration tests (to ensure the new implementation works the same way).
* Add specific functions to set and get secrets.
=> Rework secrets

charmcraft.yaml, lib/charms/postgresql_k8s/v0/postgresql_tls.py, lib/charms/rolling_ops/v0/rollingops.py, lib/charms/tls_certificates_interface/v1/tls_certificates.py, metadata.yaml, requirements.txt
* PostgreSQL charm needs to have a way to enable TLS in the connections between instances and from the client applications to the PostgreSQL server.
* This PR starts to solve that issue by adding some files needed to interact with https://github.com/canonical/tls-certificates-operator (to later, in the [next PR](https://github.com/canonical/postgresql-k8s-operator/pull/36), request TLS certificates and load them).
* The larger diff presented by the number of changed lines doesn't reflect what needs to be reviewed (which is a small part of the changes of this PR).
* Files that were `IMPORTED` and can be `IGNORED`:
* lib/charms/rolling_ops/v0/rollingops.py
* lib/charms/tls_certificates_interface/v1/tls_certificates.py
* You can `FOCUS` your review on:
* …
=> TLS relations files

lib/charms/postgresql_k8s/v0/postgresql.py, src/charm.py, src/patroni.py, src/resources.yaml, tests/integration/helpers.py, tests/integration/new_relations/test_new_relations.py, tests/unit/test_charm.py, tests/unit/test_patroni.py
* When relating the PostgreSQL k8s charm with other charm before the PostgreSQL charm is fully initialised (in an Active state), we can face some errors related to database connection problems. This can be checked by testing the relation between this charm and the PgBouncer k8s charm.
* Those problems happen due the PostgreSQL charm primary k8s endpoint/service is not yet correctly pointing to the primary pod (it takes some time to work).
* Jira issue: [DPE-701](https://warthogs.atlassian.net/browse/DPE-701)
* Avoid setting the `cluster_initialised` flag (that is checked in multiple charm events) before the primary endpoint/service is fully ready by checking its accessibility.
* Files to `FOCUS` when reviewing this PR:
* `src/charm.py`: has the call to the check, an update to the upgrade …
=> Add check for primary endpoint ready

actions.yaml, src/charm.py, src/constants.py, src/patroni.py, templates/patroni.yml.j2, tests/integration/helpers.py, tests/integration/test_charm.py, tests/integration/test_tls.py, tests/unit/test_patroni.py
* Jira issue: [DPE-700](https://warthogs.atlassian.net/browse/DPE-700)
* PostgreSQL needs some initial settings for backups and rewind operations (synchronisation of the data between a primary and the replicas after a replica is promoted to primary).
* We also need to ensure that a rewind operations (the ones using the [pg_rewind](https://www.postgresql.org/docs/current/app-pgrewind.html) tool) are done using connections encrypted by TLS.
* Add the following settings for backup operations:
* achieve_mode=on
* archive_command=/bin/true
* wal_level = logical
* Add the following settings for rewind operations:
* remove_data_directory_on_rewind_failure = true
* remove_data_directory_on_diverged_timelines = true
Add a user for pg_rewind and test that it uses TLS when connecting to other …
=> Add initial backup and rewind settings

templates/patroni.yml.j2
Revert postgres password encryption from SCRAM (the new default in version 14) to the old version 12 default (md5). 
- Updating postgres to version 14 has caused the default password encryption to change to SCRAM. While this is a good thing, it breaks the md5 password hashing that pgbouncer uses. We can't yet move to SCRAM in pgbouncer, at least until TLS exists, so for now we can downgrade postgres to md5, and we'll reinstate SCRAM when we're ready.
- This PR is currently running tests, but we're technically _reverting_ functionality so everything should run correctly.
=> Reverted password encryption to md5

lib/charms/postgresql_k8s/v0/postgresql_tls.py, src/charm.py, tests/integration/test_tls.py, tests/unit/test_postgresql_tls.py
When the postgres bundle is deployed, the TLS relation is created before pebble is ready, so the deployment fails. Therefore, this container handles the ConnectionError thrown when we try to connect to the workload container.
=> Updated tls _on_certificate_available event handler to defer on pebble ConnectionError

lib/charms/postgresql_k8s/v0/postgresql_tls.py, lib/charms/tls_certificates_interface/v1/tls_certificates.py, src/charm.py, tests/unit/test_postgresql_tls.py, tox.ini
* Jira issue: [DPE-844](https://warthogs.atlassian.net/browse/DPE-844)
* The k8s services that are created by the charm to redirect traffic to the primary and the replicas were not part of the certificate signing request sent to the TLS certificates operator.
* With that, in the first test run on a fresh microk8s installation the charm got stuck trying to call the Patroni REST API without success, as the hostname doesn’t match with the ones from the certificate. This was not happening in other test runs, but could happen in other situations. to the charm sending a certificate signing request (CSR) with it's IP address as a DNS name instead of an IP address.
* Update the code to add those services in the certificate signing request.
* You can `FOCUS` on the following files when reviewing: …
=> Fix SANs list

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/enhancement_proposal.yml, .github/pull_request_template.md, .github/workflows/issues_to_jira.yaml
GH labels are necessary to create Jira bugreports and stories properly. The templates helps to create common style bugreports and pull requests.
=> DPE-994 Improve GH->Jira sync and introduce templates and labels

lib/charms/postgresql_k8s/v0/postgresql.py, src/charm.py, src/relations/db.py, src/relations/postgresql_provider.py, tests/integration/new_relations/test_new_relations.py, tests/integration/test_tls.py
* [DPE-1024](https://warthogs.atlassian.net/browse/DPE-1024)
* Low log verbosity when deferring events within the charm
* [DPE-995](https://warthogs.atlassian.net/browse/DPE-995)
* #64
* Re-relating an application with the charm breaks due to insufficient privileges on dangling DB objects
* Add debug log messages on event deferrals
* Add more grants when reestablishing relations
* Added log messages within the charm, didn't touch or check library code deferrals
* Grants are happening in the postgresql_k8s library, it will need to be republished
* Grants should be given for tables, sequences and functions on all schemas for the new user
*  Reestablish relation new database relations integration test
*  Fixes insufficient privileges grant when reestablishing a relation
=> DPE-1024 DPE-995 Increase log verbosity and fix reestablishing relations

.github/workflows/issues_to_jira.yaml
The newly created issue on GH should have Jira's "component" correctly and automatically set.
The component value is coming from GH Secrets.
Can be tested on GH after merging only. Suppose to be the last part in the puzzle. 
No need to mention in release notes.
=> Add Jira 'component' to GH->Jira sync

.github/workflows/release.yaml
As the `ubuntu-latest` GH runner image (it's still being updated on other places) was updated to jammy, the step that publishes the charm broke (due to using `--destructive-mode`).
We can see the issue on https://github.com/canonical/postgresql-k8s-operator/actions/runs/3685747468/jobs/6238552232.
Pin focal runner image (`ubuntu-20.04`) on release workflow.
The bases on `charmcraft.yaml` weren't updated to jammy as there are some issues related to `psycopg2` (the library that is used by the charm to connect to the database) and jammy.
Tested `sudo charmcraft pack --destructive-mode --quiet` manually on a focal VM.
Pin focal runner image on release workflow.
=> Pin OS on release workflow

.github/workflows/release.yaml
GitHub Actions are not happy using the old version:
> Run canonical/charming-actions/upload-charm@2.0.0-rc
> /usr/bin/sudo snap install charmcraft --classic --channel latest/stable
> charmcraft 2.1.0 from Canonical** installed
> /usr/bin/sudo charmcraft pack --destructive-mode --quiet
> No suitable 'build-on' environment found in any 'bases' configuration.
> Full execution log: '/root/snap/charmcraft/common/cache/charmcraft/log/charmcraft-20221213-165944.902276.log'
> Error: The process '/usr/bin/sudo' failed with exit code 1
> Error: Error: The process '/usr/bin/sudo' failed with exit code 1
While we are here, bump 'check-libraries' to the latest version too.
Bump charming-actions to the latest release 2.1.1
Tested for other our repos already. It looks OK.
Bump GH Action …
=> Bump charming-actions to the latest 2.1.1

src/charm.py, src/relations/db.py, tests/integration/test_db.py, tox.ini
* [DPE-1034](https://warthogs.atlassian.net/browse/DPE-1034)
* Relating with Indico using the legacy db interface hangs
* Changed where the charm was looking for if extensions were enabled
* The Postgresql charm should block in case relation extensions are enabled, but it was looking for them in the relation databags, not in the event data
* The Indico charm was likely waiting for requested extensions to be enabled, so it kept on waiting for the database relation even after the Postgresql charm believed to be done
* Added pytest-asyncio to suppress unit test asyncio_mode warning
Fixes bug in preventing relation extensions
[DPE-1034]: https://warthogs.atlassian.net/browse/DPE-1034?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DPE 1034 Preventing extensions enabled through relations

lib/charms/postgresql_k8s/v0/postgresql.py, tests/integration/new_relations/application-charm/metadata.yaml, tests/integration/new_relations/application-charm/src/charm.py, tests/integration/new_relations/test_new_relations.py
Jira issue: [DPE-991](https://warthogs.atlassian.net/browse/DPE-991)
When a charm relates to the database interface without providing a database name and later the relation is removed the PostgreSQL charm tries to delete the database user that was not created (because the database user is only created if the relation is complete: the other application needs to provide a database name for that).
Check whether the database user exists before the charm tries to delete it.
The solution was implemented in the charm library, so it can be imported on the VM charm (the charm that was tested and initially faced the issue) on https://github.com/canonical/postgresql-operator/pull/51.
As the issue also happens on this charm, it's worth to have the fix on the charm library.
A test simulating a …
=> Fix delete user call when user was not created before

tests/integration/test_db.py
Because I didn't merge main into [this PR](https://github.com/canonical/postgresql-k8s-operator/pull/74), some duplicated code was added when merging into main, [making the lint job fail](https://github.com/canonical/postgresql-k8s-operator/actions/runs/3904228221/jobs/6669720049#step:4:10).
Remove the duplicate code.
Remove duplicate code.
=> Remove duplicate helper function

src/relations/db.py, tests/integration/test_db.py
* [DPE-1085](https://warthogs.atlassian.net/browse/DPE-1085)
* When the charm blocks due to a legacy relation requesting an extension nothing clears up the blocked status
* Add check at the end of  `_on_relation_departed()` to see if there are relations requesting extensions and setting the status to active if none
* Extended the indico integration test to check if the blocked status is cleared up
* Clear up blocked status when no relations requesting extensions are left
[DPE-1085]: https://warthogs.atlassian.net/browse/DPE-1085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> DPE-1085: Clear up block status due to extensions and integration test

src/relations/db.py
* [DPE-1085](https://warthogs.atlassian.net/browse/DPE-1085)
* `_on_relation_broken` appears to be a more appropriate place for unblocking the charm
* Move the check to `on_relation_broken`
* `_on_relation_departed` would unblock the charm if we scale down the related application requesting extensions even if we have other units of it left
[DPE-1085]: https://warthogs.atlassian.net/browse/DPE-1085?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Move clearing of extensions Blocked status to on_relation broken

lib/charms/postgresql_k8s/v0/postgresql_tls.py, requirements.txt, tests/unit/test_postgresql_tls.py
* [DPE-1081](https://warthogs.atlassian.net/browse/DPE-1081)
* VM charm [PR#53](https://github.com/canonical/postgresql-operator/pull/53)
* Moving fixes from the VM charm to K8S charm to publish the updated charm library
* TLS tests broke with the update of ops to 1.5.4, fixes to the library should remedy this
* Updating ops framework to 1.5.4
* Updating postgresql_tls charm lib to 0.5
[DPE-1081]: https://warthogs.atlassian.net/browse/DPE-1081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Updating ops framework and postgresql_tls charm lib

.github/workflows/ci.yaml, .github/workflows/release.yaml
We do not have a well visible warning for the outdated libraries in use
and we do not publish them automatically.
We need to be sure our libraries are up-2-date on
the new pull-request and pushed to charmhub on
merging PR and publishing the new charm revision.
Use new `charming-action/release-libraries` and run `check-libraries` on PR (ci.yaml).
GH Actions.
Use new `charming-action/release-libraries` and run `check-libraries` on PR (ci.yaml).
=> Run check-lib as a part of ci.yaml CI/CD

.github/workflows/release.yaml, CONTRIBUTING.md, charmcraft.yaml, tests/integration/ha_tests/application-charm/charmcraft.yaml, tests/integration/ha_tests/conftest.py, tests/integration/ha_tests/test_self_healing.py, tests/integration/helpers.py, tests/integration/new_relations/application-charm/charmcraft.yaml, tests/integration/new_relations/test_new_relations.py, tests/integration/test_charm.py, tests/integration/test_db_admin.py, tests/integration/test_password_rotation.py, tests/integration/test_tls.py
Jira issue: https://warthogs.atlassian.net/browse/DPE-1411
The charm is still on Focal.
Upgrade all the bases and all the deployments to use Jammy.
The Discourse charm started to request extensions (the version that requests extensions was promoted to stable today - 2023-02-28): https://github.com/canonical/discourse-k8s-operator/commit/08830d595de9bd391e74d5b0740f0390b8861a1e. So, the test was changed in this PR.
Used the existing tests to confirm that the charm works on Jammy.
Upgrade charm to Jammy.
=> Upgrade to jammy

tests/integration/ha_tests/test_self_healing.py, tests/integration/test_charm.py, tests/integration/test_db.py, tests/integration/test_tls.py
Jira issue: [DPE-1356](https://warthogs.atlassian.net/browse/DPE-1356)
Some integration tests fail transiently and sometimes make the development slower.
Mark them as unstable and create tasks for solving each of them.
New Jira issues were created for each of the tests that need to be fixed. They're listed on [DPE-1356](https://warthogs.atlassian.net/browse/DPE-1356?focusedCommentId=200066).
The TLS tests was changed to match the text in the logs without all the details related to TLS version or bits (because it may change when updating the database version).
Tested on multiple runs locally and on CI.
Mark unstable tests.
[DPE-1356]: https://warthogs.atlassian.net/browse/DPE-1356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Mark unstable tests

src/charm.py, tests/integration/helpers.py
Jira issues: [DPE-1127](https://warthogs.atlassian.net/browse/DPE-1127) and [DPE-1378](https://warthogs.atlassian.net/browse/DPE-1378)
Use unique DNS names for each service port (using the same names that are already being used by the primary and replicas k8s services).
The test helpers functions got some new k8s resources added because they were already created before this change, but without the right labels. This PR also fixed it.
Closes #99.
Tested manually and checked the logs.
Use unique DNS names for each service port.
[DPE-1127]: https://warthogs.atlassian.net/browse/DPE-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-1378]: https://warthogs.atlassian.net/browse/DPE-1378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …
=> Fix duplicate K8S service ports names

src/charm.py, tests/integration/helpers.py, tests/integration/test_password_rotation.py, tests/unit/test_charm.py
Jira issue: [DPE-1489](https://warthogs.atlassian.net/browse/DPE-1489)
All the passwords returned by the get and set password actions have the username as a prefix, but who requested it already knows the user, so it's not needed to have it specified in the action result, only the password.
Remove the username prefix from the password key in the actions results.
Reference: https://github.com/canonical/mongodb-operator/pull/172#discussion_r1115859485 (request from Mykola).
I also contacted Marc about the Zookeeper charms.
Fixed the existing tests.
Simplify password parsing in action results.
[DPE-1489]: https://warthogs.atlassian.net/browse/DPE-1489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Simplify password parsing in action results

tests/integration/conftest.py
Jira issue: [DPE-1504](https://warthogs.atlassian.net/browse/DPE-1504)
Yesterday the AWS credentials were changed to the team credentials.
A test failed due to that because those credentials work only for the team bucket (that should be used instead the personal bucket): https://github.com/canonical/postgresql-k8s-operator/actions/runs/4436528202/jobs/7785176423
The bucket name and its region were changed in the test code (to use the team bucket).
In the future we can probably move the bucket and region names to environment variables.
Used the existing tests to validate the change.
Fix AWS bucket name and region in integration test.
[DPE-1504]: https://warthogs.atlassian.net/browse/DPE-1504?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix AWS bucket name and region

src/backups.py
Jira issue: [DPE-1507](https://warthogs.atlassian.net/browse/DPE-1507)
Failed backups are being considered in the restore action.
Add a flag to the function that list backup ids to return or not failed backups.
Check for failed backups in `_on_create_backup_action`.
Don't consider failed backups in `_on_restore_action`.
Change copied from https://github.com/canonical/postgresql-operator/pull/83#discussion_r1138186416.
Unit and integration tests for the backup/restore features will be implemented on [DPE-556](https://warthogs.atlassian.net/browse/DPE-556).
Don't consider failed backups when restoring.
[DPE-1507]: https://warthogs.atlassian.net/browse/DPE-1507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DPE-556]: …
=> Don't consider failed backups when restoring

lib/charms/postgresql_k8s/v0/postgresql_tls.py, tests/unit/test_postgresql_tls.py
Jira ticket: [DPE-1532](https://warthogs.atlassian.net/browse/DPE-1532)
To implement https://warthogs.atlassian.net/browse/DPE-1271  it’s needed that the TLS Server finds in the certificate the IP address of the unit that is connecting to it.
Currently, it’s not possible due to https://github.com/pgbackrest/pgbackrest/issues/1977.
Add the IP address also to the DNS SANs list (like "DNS:1.2.3.4" entries).
This charm library will be updated later in the VM charm repository.
Tested manually in the VM charm.
Add IP address to DNS SANs list.
[DPE-1532]: https://warthogs.atlassian.net/browse/DPE-1532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add IP address to DNS SANs list

CONTRIBUTING.md, README.md, docs/landing.md, docs/tutorial.md
[DPE-1302](https://warthogs.atlassian.net/browse/DPE-1302)
Our charm had lack of tutorials and discorse manuals.
It is a first commit to provide initial tutorial guide.
Manually, while preparing manual.
Add Discorse Tutorial and Landing pages. Updated README and CONTRIBUTING guides.
[DPE-1302]: https://warthogs.atlassian.net/browse/DPE-1302?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Tutorial and Landing page and update README and CONTRIBUTING guides

docs/reference/backups.md
Jira ticket: [DPE-1570](https://warthogs.atlassian.net/browse/DPE-1570)
There are no diagrams for backup/restore logic.
Add diagrams for S3 credentials changed, create backup, list backups and restore hooks.
As some other diagrams are still missing, like for TLS relation events, additional notes were added below the diagrams.
Add backup diagrams.
[DPE-1570]: https://warthogs.atlassian.net/browse/DPE-1570?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Backup diagrams

src/charm.py, tests/unit/test_charm.py
* [DPE-1514](https://warthogs.atlassian.net/browse/DPE-1514)
* Sets the workload version to what Pgbouncer reports as it's version
* Using the version set in the snap manifest
* Sets the workload version
[DPE-1514]: https://warthogs.atlassian.net/browse/DPE-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Setting workload version to snap in rock version

poetry.lock, src/charm.py, tests/unit/test_patroni.py
[Sometimes](https://github.com/canonical/pgbouncer-k8s-operator/actions/runs/4719644966/jobs/8393434027) there is an unhandled exception while regenerating the patroni configuration due to the charm being unable to read the postgresql version from the workload container
Check if the workload container is connectable before regenerating the config
=> Update conf only when the container is connectable

src/backups.py, tests/unit/test_backups.py
The backup and restore features don't have unit tests.
Add unit tests for 1/3 of the implemented methods.
The remaining 2/3 of unit tests were implemented on https://github.com/canonical/postgresql-k8s-operator/pull/165 and https://github.com/canonical/postgresql-k8s-operator/pull/166 to keep this PR small.
A fix was made on `src/backups.py` to really rollback the stanza name when the `pgbackrest check command fails`. It was incorrectly setting the stanza name again in the relation data, instead of clearing it.
=> [DPE-556] Add 1st batch of backup/restore unit tests

src/backups.py, tests/unit/test_backups.py
The backup and restore features don't have unit tests.
Add unit tests for 1/3 of the implemented methods.
The remaining 2/3 of unit tests were implemented on https://github.com/canonical/postgresql-k8s-operator/pull/164 and https://github.com/canonical/postgresql-k8s-operator/pull/165 to keep this PR small.
The logic that fixes slashes in the S3 path was moved in `src/backups.py` to handle that in the right place (after a default path is set).
=> [DPE-556] Add 3rd batch of backup/restore unit tests

src/relations/db.py, tests/integration/helpers.py, tests/integration/test_db.py, tests/integration/test_db_admin.py, tests/unit/test_db.py
The Discourse K8S charm test was disabled on https://github.com/canonical/postgresql-k8s-operator/pull/94 because it started to request extensions through the relation.
In this PR, we enable the test back again and use the [new plugins/extensions support](https://github.com/canonical/postgresql-k8s-operator/pull/170) to make it work back again.
Now, Discourse needs only the `db` relations (rather than the `db-admin` relations, that was previously used by Discourse itself to install the extensions). So, the test was moved to the `db` relation integration test file.
Some unit tests were copied from https://github.com/canonical/postgresql-operator/pull/139 to improve the coverage of this charm.
=> [DPE-2057] Enable Discourse-K8S test

src/backups.py, src/charm.py
We are not logging the success or failure of both the `create-backup` and `restore` actions in a way that is easy for other applications to parse the logs related to success or failure on those operations.
Log failures (as errors) and successes (as info) to the debug log. The failures have prefix `Backup failed`/`Restore failed`, the successes have prefix `Backup successful`/`Restore successful`.
The `Restore successful` message can be logged only after Patroni starts (which happens some time after the execution of the `restore` action).
=> [DPE-1916] Backup and restore log messages

metadata.yaml
Security scan report:
```
Revision r61 (amd64; channels: 14/edge)
* libc-ares2: 6164-1
```
Rebuild and update rock
=> Update OCI due to outdated packages

.github/workflows/release.yaml
Charm is published to charmhub on each push to main even if there are no changes to the charm itself
Try to limit the amount of releases based on the content of the push
=> Internal changes to the charm shouldn't be released

src/upgrade.py, tests/unit/test_upgrade.py
The upgrade changed event is being fired too early on https://github.com/canonical/pgbouncer-k8s-operator/actions/runs/5808523985/job/15745553754#step:7:228, which causes the errors, when the container is not available yet to connect and retrieve the ROCK PostgreSQL version.
Run the event logic (call to `update_config`) only when needed (when the member is ready - during an pre upgrade check), and not when the charm starts.
Tested through https://github.com/canonical/pgbouncer-k8s-operator/pull/126.
=> [DPE-2355] Fix upgrade changed event executing too early

tests/integration/test_tls.py
Missing await in the tls tests causes frequent errors.
=> [MISC] Missing await

metadata.yaml
We cannot upgrade from `14/stable` to `14/edge` due to storage changes:
```sh
➜  ~ juju deploy postgresql-k8s --channel 14/stable --trust
Located charm "postgresql-k8s" in charm-hub, revision 73
Deploying "postgresql-k8s" from charm-hub charm "postgresql-k8s", revision 73 in channel 14/stable on jammy
➜  ~ juju refresh postgresql-k8s --channel 14/edge
Added charm-hub charm "postgresql-k8s", revision 117 in channel 14/edge, to the model
ERROR Juju on containers does not support updating storage on a statefulset.
The new charm's metadata contains updated storage declarations.
You'll need to deploy a new charm rather than upgrading if you need this change.
not supported (not supported)
```
Juju issue: https://bugs.launchpad.net/juju/+bug/1995074
The change that broke the possibility of the …
=> [DPE-2392] Fix storage for upgrade

.github/workflows/ci.yaml, tests/integration/test_db.py
The indico legacy rel test is failing frequently on juju 3. Indico seems stuck in idle/active until the test times out or is cancelled.
Temporarily disable the test.
Checking if things are better in juju 3.1.6 on https://github.com/canonical/postgresql-k8s-operator/pull/249
=> [MISC] Temporarily disable indico tests on Juju 3

config.yaml, lib/charms/postgresql_k8s/v0/postgresql.py, src/charm.py, src/patroni.py, templates/patroni.yml.j2, tests/integration/helpers.py, tests/integration/new_relations/test_new_relations.py, tests/integration/test_charm.py, tests/integration/test_password_rotation.py
Profiles support missing from PG
* Created method to build postgresql parameters, based on profile.
* using patroni template to configure parameters
* defaults to `production` profiles (better performance, as done for mysql)
* parameter building is a MVP:
* `testing` profile set no extra parameters
* `production` set's minimal needs for IS scenarios (see follow-up)
* has `available_memory` input, but is not in use: logic is TBD
* integration tests uses `testing` profile
1. Proper memory detection for parameter calculation
1. React `on-config-change` to allow inflight profile change
=> DPE-2616 Basic profile support

src/backups.py, tests/unit/test_backups.py
* All units try to create a bucket and all units will block if it fails
* Backup blocked statuses are not cleared if the s3 relation is removed.
* Only the leader should check the s3 creds and bucket
* Clear up the blocked statuses when the s3 creds are gone
=> [DPE-2626][DPE-2627] Create bucket once and clear up blocked statuses

src/backups.py, tests/unit/test_backups.py
The data directory cannot be deleted during the restore operation on storages provided by external providers (like EBS and cloud storages).
Remove and recreate the data directory using the root user, which has privileges in the mounted storage.
Fixes https://github.com/canonical/postgresql-k8s-operator/issues/265.
=> [DPE-2664] Fix empty data files on remote storage

src/charm.py, src/patroni.py
If we have a cluster of two or more units, scale it down to 1 unit, create a backup, restore the backup and scale up back again, the replication stop working due to reuse of the storage.
In that situation, as we see a huge replication lag, we need to reinitialise the replicas.
Fixes https://github.com/canonical/postgresql-k8s-operator/issues/262.
=> [DPE-2657] Fix replication after restore

src/grafana_dashboards/postgresql-metrics.json
Buffers and Checkpoint Stats are broken due to changes upstream.
Switch to updated metrics names.
Fixes: #276
=> Fixes broken postgresql dashboard queries

src/grafana_dashboards/postgresql-patroni-metrics.json
The Patroni dashboard displays an undecipherable string as the labels for graphs.
Switch labels to juju_unit.
Fixes #274
=> Change Patroni dashboard labels to display unit.

lib/charms/data_platform_libs/v0/upgrade.py, lib/charms/postgresql_k8s/v0/postgresql.py, src/relations/db.py, src/relations/postgresql_provider.py, tests/unit/test_db.py
New databases do not consider already enabled extensions.
Check extensions conf when creating a database and enable extensions.
=> [DPE-2569] Extensions not enabled when database is created

.github/workflows/ci.yaml, .github/workflows/lib-check.yaml, .github/workflows/release.yaml, lib/charms/data_platform_libs/v0/upgrade.py
Checking charm libs requires credentials that are not available to contributors outside of the DPE team.
Split the checking action in a separate workflow that is not run on forked PRs.
=> [DPE-2804] Split off lib-check

.github/workflows/ci.yaml, lib/charms/data_platform_libs/v0/data_interfaces.py, pyproject.toml, tests/integration/test_backups.py
Can't run the backup integration tests without accessing secrets
Skip tests if PR from a forked repo
Test external PR: https://github.com/canonical/postgresql-k8s-operator/pull/311
=> [DPE-2804] Conditionally skip backup tests

.github/workflows/ci.yaml
Secrets tests were always skipped.
Secrets tests are only sometimes skipped.
=> [DPE-2804] Fix backup condition check

lib/charms/postgresql_k8s/v0/postgresql.py, src/charm.py, src/relations/db.py, tests/unit/test_db.py
Starting a connection for each db to enable or disable plugins will take more and more time as the number of plugins increases.
Open a single connection per db and enable or disable the plugins in one go.
=> [DPE-2903] Toggle plugins in one go

.github/workflows/ci.yaml, .github/workflows/release.yaml, .github/workflows/sync_issue_to_jira.yaml, poetry.lock, pyproject.toml, tests/integration/ha_tests/helpers.py, tests/integration/ha_tests/test_replication.py, tests/integration/ha_tests/test_self_healing.py, tests/integration/ha_tests/test_upgrade.py, tests/integration/ha_tests/test_upgrade_from_stable.py, tests/integration/helpers.py, tests/integration/new_relations/test_new_relations.py, tests/integration/test_backups.py, tests/integration/test_db.py
* Indico charm was ported to the new interface
* No tests left checking for legacy interface extension behaviour
* Split the old indico test into one checking legacy relations and one testing that indico deploys with the new interface
=> [DPE-2844] New interface indico test and new legacy extensions test

lib/charms/postgresql_k8s/v0/postgresql.py, src/charm.py, src/relations/db.py, src/relations/postgresql_provider.py, tests/integration/new_relations/test_new_relations.py, tests/integration/test_db.py, tests/unit/test_charm.py, tests/unit/test_db.py, tests/unit/test_postgresql.py, tests/unit/test_postgresql_provider.py
Some charms like Discourse-K8S need to have the ownership of the tables and other objects in a database to correctly run its migrations if a database from a previous Discourse installation is used, otherwise it will not complete the migrations and will throw an error. Also, the existing Discourse K8S test was marked as `unstable` in the past because that charm was migrated from the legacy to the modern relation interface.
If the relation between PostgreSQL and Discourse K8S (or any other charm), continue with the same behaviour, but after another instance of the charm is related to the PostgreSQL again, requesting the same database, check if there is no other application related and that previously requested the same database. If so, change the ownership of the objects in the database to …
=> [DPE-2740] Handle tables ownership

src/backups.py, tests/integration/test_backups.py, tests/unit/test_backups.py
In https://github.com/canonical/postgresql-k8s-operator/issues/335, the new cluster where the user tried to restore the backup had the same name as the cluster the backup was made from. As we're checking only the cluster/stanza name to set the blocked status, informing the user that there are backups from another cluster in the repository, the blocked status is not set for this specific case.
Use the PostgreSQL installation system id to differentiate clusters.
=> [DPE-3061] Check system identifier in stanza

lib/charms/postgresql_k8s/v0/postgresql.py, src/charm.py, tests/unit/test_charm.py, tests/unit/test_postgresql.py
The validation for the `shared_buffers` parameter was not correct. The calculus of the maximum allowed shared buffers value was not correctly converting the available memory for that to the same unit as the `shared_buffers` parameter that the user informs.
Also, the `effective_cache_size` parameter did not consider the user-provided `shared_buffers` value.
One last issue: sometimes, the restart of the PostgreSQL database was not triggered because Patroni hadn't finished reloading the configuration (even after 10 seconds).
Fix the calculus of the maximum allowed shared buffers value to be in the same unit as the user-provided value.
Considered the user-provided shared buffers value for the effective cache size parameter calculus.
An improved retry mechanism was added to check whether a …
=> [DPE-3594] Fix shared buffers validation

lib/charms/postgresql_k8s/v0/postgresql.py, tests/unit/test_postgresql.py
If we relate a charm like the MAAS operator to the PostgreSQL operator, remove the relation and relate again, then MAAS doesn't have access to the previously created PostgreSQL large objects.
https://github.com/canonical/postgresql-k8s-operator/issues/389
When a charm is related again to the PostgreSQL operator, give the ownership of the existing large objects to that charm user, as we already do for tables and other objects.
=> [DPE-3551] Fix large objects ownership

src/charm.py, src/utils.py
support for k8s allocatable cpu is only considering core count (as integer, microk8s default), and not millis (e.g. 7500m)
Add support for k8s allocatable cpu in millis
fixes #409
=> DPE-3695 support cpu in millis

README.md
Docs sync workflow is not yet added, so the badge doesn't render.
Removing the badge for now, to be added after `discourse-gatekeeper` integration.
=> Removed doc sync workflow badge

src/charm.py, src/config.py, tests/integration/test_config.py
All this cases should be covered:
- Charge each charm config option using clusterized app and make sure changes are 
applied without error (and without downtime if possible):
- check values boundaries (e.g. try 42 where 1-10 are allowed)
- check types (e.g. try 42 where boolean true/false are expected)
- check invalid config values (see the “test string” below)
=> Add `test_config_parameters` test

src/charm.py, tests/integration/test_config.py, tests/unit/test_charm.py
`_validate_config_options` connecting to the database will be done only in on_config_changed
Port of https://github.com/canonical/postgresql-operator/pull/395
=> [DPE-3593] Only check config values against the DB in on_config_changed

lib/charms/postgresql_k8s/v0/postgresql.py, poetry.lock, pyproject.toml, src/backups.py, src/charm.py, src/config.py, src/relations/db.py, src/relations/postgresql_provider.py, src/upgrade.py, src/utils.py, tests/integration/ha_tests/helpers.py, tests/integration/ha_tests/test_self_healing.py, tests/integration/helpers.py, tests/integration/new_relations/test_new_relations.py, tests/integration/test_backups.py, tests/integration/test_charm.py, tests/integration/test_tls.py, tests/unit/conftest.py, tests/unit/test_backups.py, tests/unit/test_charm.py, tests/unit/test_postgresql.py, tox.ini
=> [MISC] Switch to ruff formatter

tests/integration/test_db.py, tests/integration/test_db_admin.py
User should be created on a relation-joined event, and the user should be dropped on a relation-departed event
Added missed for checking user existence after application removed
=> Check user existence after relation broken for `db` and `db-admin` interfaces

src/upgrade.py
The message that blocks an upgrade if the unit number 0 is neither a primary nor a sync-standby is shown only in the logs, making the user think that there is an issue with the cluster.
Show the message in the action error output.
=> [DPE-3803] Show error on upgrade action

src/charm.py, tests/unit/test_charm.py
The `Primary` status message is not shown when the first unit is ready to accept connections (i.e., the bootstrap of the cluster has been completed).
Set the `Primary` status message in the primary unit right after it's ready to accept connections (while still considering the K8s primary service).
=> [DPE-3570] Add primary status message after cluster bootstrap

tests/integration/helpers.py, tests/integration/test_tls.py
As described [here](https://github.com/canonical/postgresql-k8s-operator/issues/445) encrypted connection between replicas should be exists when TLS enabled
Updated TLS test, added check for replicas encrypted connection
Imported from [VM](https://github.com/canonical/postgresql-operator/pull/437)
=> Added `check_tls_replication` for checking replicas encrypted connection

src/charm.py, tests/unit/conftest.py, tests/unit/test_backups.py, tests/unit/test_charm.py, tests/unit/test_db.py, tests/unit/test_patroni.py, tests/unit/test_postgresql.py, tests/unit/test_postgresql_provider.py, tests/unit/test_postgresql_tls.py, tests/unit/test_upgrade.py, tests/unit/test_utils.py
Follow-up to DPE-2674 in https://github.com/canonical/postgresql-operator/pull/425
=> [DPE-4068] Convert all tests from unittest to pytest + enable/disable secrets in every test

.github/workflows/ci.yaml, tests/unit/conftest.py, tox.ini
No reason for having two separate suites for juju2 and juju3 now that we have pytest structure to easily auto-use fixtures.
remove both suites, include auto-use fixture
=> [MISC] Unify juju2 and juju3 test suites

src/charm.py
Pgbackrest service and configuration are not enabled if a pod is recreated
Render and start pgbackrest ssl service on pebble ready
=> [DPE-2671] Rerender and reenable pgbackrest config and service

src/relations/async_replication.py
When retrieving the app secret containing the operator’s user passwords in the promotion of a cluster in an async replication setup, the charm fails to try to get the secret labelled as `postgresql-k8s.app`  instead of `database-peers.postgresql-k8s.app`.
This happened after merging https://github.com/canonical/postgresql-k8s-operator/pull/447 to the main branch (which had some changes in the secret handling, which were not merged before to that PR branch).
Fix the secret label.
This is a quick fix. To improve it, it should be moved to a common `data_interfaces` interface.
There is a revision in the `14/edge/async-replication` channel with the change from this PR.
=> [DPE-4296] Fix secret label

src/charm.py, src/patroni.py, tests/integration/test_backups.py
Tests are failing much more frequently in the CI: https://github.com/canonical/postgresql-k8s-operator/actions/runs/9174854748/job/25300990262 and https://github.com/canonical/postgresql-k8s-operator/actions/runs/9174950263/job/25327421131
3 changes:
- https://github.com/canonical/postgresql-k8s-operator/pull/457: for errors related to event of TLS removal
- revert `wait_for_idle=True` change implemented in [this commit](https://github.com/canonical/postgresql-k8s-operator/commit/1a25c3929747beea7e78467b169b2b345b29d470#diff-8086ca56f97e29bae41b7541a1852d62cf6a6c5b475a9f375a1f6a6b7174c3f0)
- Increase retries on `reload_patroni_configuration` to avoid connectivity errors like the one [here](https://github.com/canonical/postgresql-k8s-operator/actions/runs/9174854748/job/25291314964)
=> [MISC] Fine-tune test_backup.py + Ignore secret remove hook

src/charm.py, tests/integration/test_backups.py
Port of https://github.com/canonical/postgresql-operator/pull/467
* The charm should not restore the blocked status if the blocking condition is no longer valid
* Skip delete pod test in backups if there are no secrets
=> [DPE-4336] Reset active status when removing extensions dependency block

lib/charms/data_platform_libs/v0/s3.py, src/backups.py, templates/pgbackrest.conf.j2, tests/unit/test_backups.py
Link to issue: https://warthogs.atlassian.net/browse/DPE-4401
Link to spec: https://docs.google.com/document/d/1WWMt_Q71cUIrpfYirp5TRCdkJXMjFSWCH6CTnKrO4YA/edit
The parameter `delete-older-than-days` (from s3-integrator) is used to set up retention time (in days) as a pgBackRest parameter, allowing for uses to configure a retention policy for their backups.
- Fetches `delete-older-than-days` parameter from S3-integrator relation data.
- Includes `data_platform_libs` patch from https://github.com/canonical/data-platform-libs/pull/168
- Set pgBackRest parameters `repo1-retention-full` and `repo1-retention-full-type=time`
- Modifies unit tests to check for a retention time in days.
- Tested locally,
- Unit tests assures `delete-older-than-days` is correctly fetched from s3 parameters,
- …
=> [DPE-4401] Add retention time for full backups

actions.yaml, src/backups.py, src/constants.py, tests/integration/test_backups.py, tests/unit/test_backups.py
- Adds support for incremental type backups
- Proper naming usage (in accordance to [spec](https://docs.google.com/document/d/1WWMt_Q71cUIrpfYirp5TRCdkJXMjFSWCH6CTnKrO4YA/edit))
Follow-up to #476 
https://warthogs.atlassian.net/browse/DPE-4475 for including incremental backup check in integration test.
=> [DPE-4464] Add Incremental backup support + proper type naming

src/backups.py, tests/unit/test_backups.py
We cannot scale up if S3 and TLS relations are established. This operation leads to an error like the one below if, in the new unit, the S3 parameters relation changed event fires before the TLS files are available in the unit (and Patroni + PostgreSQL haven't started yet).
```sh
requests.exceptions.SSLError: HTTPSConnectionPool(host='10.142.152.2', port=8008): Max retries exceeded with url: /cluster (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)')))
```
Defer the S3 parameters relation changed event until that unit can do any operation related to S3 (or even connect to the other unit to check the cluster topology and verify it's not the primary unit so that it can …
=> [DPE-4456] Fix scale up with S3 and TLS relations

src/backups.py, templates/pgbackrest.conf.j2, tests/unit/test_backups.py
It's possible to configure a TLS CA chain in the S3 integrator charm. However, the PostgreSQL charm doesn't use that, so right now, it's not possible to connect to S3-compatible storages which provide a self-signed SSL certificate.
Push the TLS CA chain contents to a file and reference it in the pgBackRest configuration (and also in the boto3 calls), so it uses that CA when communicating with the S3-compatible storage.
Manual testing:
1. Build and install the MicroCeph snap from the https://github.com/marceloneppel/microceph/tree/rgw-https-support branch.
```sh
snapcraft -v
sudo snap install --dangerous microceph_*.snap
```
2. Generate the SSL files.
```sh
sudo openssl genrsa -out /var/snap/microceph/common/ca.key 2048
sudo openssl req -x509 -new -nodes -key …
```
=> [DPE-4413] Use TLS CA chain for backups

lib/charms/postgresql_k8s/v0/postgresql.py, tests/integration/new_relations/test_new_relations.py, tests/integration/test_password_rotation.py
config value `log_statement = 'ddl'` logs queries such as `ALTER USER/ROLE`, `CREATE USER/ROLE` that expose users passwords on log files.
set `log_statement='none'` when submitting sensitive queries:
```
BEGIN;
SET LOCAL log_statement = 'none';
CREATE ROLE "backup" WITH LOGIN SUPERUSER ENCRYPTED PASSWORD 'MRiT223dummy2322nHESx';
...
COMMIT;
```
New integration test failing before the change: https://github.com/canonical/postgresql-k8s-operator/actions/runs/9483057657/job/26129752923#step:21:386
... and passing after the change: https://github.com/canonical/postgresql-k8s-operator/actions/runs/9483490912/job/26131217890?pr=506#step:21:182
=> [DPE-4369] SQL queries exposing passwords on postgresql logs

src/relations/postgresql_provider.py, tests/integration/new_relations/test_new_relations.py, tests/unit/test_postgresql_provider.py
https://warthogs.atlassian.net/browse/DPE-2278 - Right now, it is up to the client application to build the connection string.
Proposed solution: use the already existing `uri` field from the `data_interfaces` lib to pass the correctly formed libpq URI [as described here](https://www.postgresql.org/docs/current/libpq-connect.html#LIBPQ-CONNSTRING-URIS) to client apps. The read-write primary endpoint is used for it.
=> [DPE-2278] Add libpq's connection string URI format to `uri` field in relation databag

lib/charms/postgresql_k8s/v0/postgresql.py, src/charm.py, tests/integration/test_plugins.py, tests/unit/test_charm.py
See https://github.com/canonical/postgresql-k8s-operator/issues/536
If the charm detects objects that depend on plugins not enabled via config (most likely because the plugin was externally enabled) It will go into blocked state and warn the user. 
The user can then decide to either: Delete the objects and proceed with the plugin disabled (without updating the config) or update the juju config option of the plugin as enabled.
Local testing works, Will add unit/integration tests shortly.
=> [DPE-4801] Block charm if plugin disable fails due to dependent objects

src/charm.py, tests/unit/test_charm.py
If Patroni needs to reinitialise the data directory in the replicas and the storage where the data directory is created is mounted without permission for the `postgres` users to write on it, Patroni will fail its operation.
Fix the permissions of the data directory parent directory to enable Patroni to move/remove directories when needed.
Fixes https://github.com/canonical/postgresql-k8s-operator/issues/460.
=> [DPE-4227] Fix storage ownership

src/backups.py, tests/unit/test_backups.py
Lack of logs when pbackrest is creating an action. Inspired by https://github.com/canonical/mysql-operator/pull/471/
Adds `stream` option to `_execute_command` that fetches from IO streams and writes them to juju logs. Unbuffered for stdout logs.
=> [MISC] More logs from pgbackrest create backup command

src/charm.py, tests/integration/ha_tests/test_self_healing.py, tests/integration/test_tls.py, tests/unit/test_charm.py
https://github.com/canonical/postgresql-k8s-operator/issues/540
- Check pebble status inside `update_status` hook. Restart if not enabled.
- Update unit tests and integrations tests.
=> [DPE-4806] Restart pebble service if it's down

src/charm.py
The new PITR test is failing on Juju 2.9 (https://github.com/canonical/postgresql-k8s-operator/actions/runs/10116043301/job/27978532633#step:26:974):
```sh
unit-postgresql-k8s-aws-0: 12:51:44 ERROR unit.postgresql-k8s-aws/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/./src/charm.py", line 2052, in <module>
main(PostgresqlOperatorCharm, use_juju_for_storage=True)
File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/venv/ops/main.py", line 551, in main
manager.run()
File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/venv/ops/main.py", line 530, in run
self._emit()
File "/var/lib/juju/agents/unit-postgresql-k8s-aws-0/charm/venv/ops/main.py", line 519, in _emit …
```
=> [DPE-4990] Fix PITR test on Juju 2.9

src/relations/postgresql_provider.py, tests/integration/new_relations/test_new_relations.py
New relations integration test had a typo in `test_invalid_extra_user_roles` where two `block_until` calls were not being properly awaited. Once those were added, the test started failing due to blocked status resolving when it shouldn't have.
- Add the necessary `await`s
- Use `continue` instead of `break` inside check loop to resolve the blocked status for invalid extra user roles.
This was previously done on VM inside https://github.com/canonical/postgresql-operator/pull/546
=> [MISC] Adds missing `await` to `invalid_extra_user_roles` integration test + fix check loop

actions.yaml
The `get-password` action has the wrong description (it was copied from the `set-password` action).
Update to use the correct description for the action (the same we have in the VM charm).
Fixes https://github.com/canonical/postgresql-k8s-operator/issues/603.
=> [DPE-5019] Fix get-password action description

config.yaml, src/charm.py, tests/unit/test_charm.py
See ticket, related to https://github.com/canonical/postgresql-operator/pull/564
=> [DPE-4889] Remove deprecated config option profile-limit-memory

src/arch_utils.py
Fixes a bug reported on https://github.com/canonical/postgresql-k8s-operator/pull/613#issuecomment-2294369041 where the import error would get re-raised because the architecture check was not working properly (returning `False` due to not finding the `.juju-charm` file). 
Use `manifest.yaml` instead of `.juju-charm`, it is a more reliable check for some reason.
CI pass (always have been, apparently jujus 2.9 and 3.4 never had the problem?) + local tests on AMD and juju 3.5 work + @marceloneppel tested on ARM + juju 3.5 and also worked. Should be fine now!
=> [DPE-4239] Use manifest file to check for charm architecture

src/charm.py
We don't know all the moments when the `leader` annotation is fixed (we know that one situation - expected - is after a scale down to 0 units and then a scale up to 1 unit), which causes the `cluster_initialised` flag to be removed from the peer relation data (this is causing issues in production like the one reported at https://github.com/canonical/postgresql-k8s-operator/issues/634).
Add a log for the `fix_leader_annotation` method so we can better understand why the issue occurs.
=> [DPE-5165] Add log for fix_leader_annotation method

src/charm.py, tests/integration/test_storage.py
The charm gives no indication of low storage space on `pgdata` folder, which can cause unexpected failures
Added check on `update_status` hook + integration test.
=> [DPE-5301] Add check for low storage space on pgdata volume

src/charm.py, tests/integration/ha_tests/helpers.py, tests/integration/ha_tests/test_restart.py, tests/integration/helpers.py
After restarting the pods of a PostgreSQL K8s charm deployment (we can use `kubectl -n dev delete pod -l app.kubernetes.io/name=postgresql-k8s` for testing), if the `stop` hook fails for some reason, the `upgrade-charm` hook won't fire when the pod is rescheduled, and no Patroni labels will be added to the pod. This makes Patroni understand that the unit is not part of the cluster, so it deletes that unit replication slot from the primary.
In the past (before https://github.com/canonical/postgresql-k8s-operator/pull/448, which added a check for `container.can_connect()`), this could happen due to a re-emitted deferred pebble-ready event:
```sh
unit-postgresql-k8s-2: 17:36:20 ERROR unit.postgresql-k8s/2.juju-log Uncaught exception while in charm code:
Traceback (most recent call last): …
```
=> [DPE-3887] Avoid replication slot deletion

src/charm.py, src/upgrade.py, tests/integration/ha_tests/test_upgrade_from_stable.py, tests/integration/helpers.py, tests/integration/new_relations/test_new_relations.py, tests/integration/test_backups.py, tests/integration/test_backups_pitr.py, tests/integration/test_charm.py, tests/unit/test_charm.py
- This PR addresses some of the sources of instability in CI, mainly those introduced with the new PITR feature. 
- Unit testing will be implemented once you are OK with the changes.
- See review comments for specific context.
=> [MISC] Fixes for PITR backup test instabilities

lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py, lib/charms/tempo_coordinator_k8s/v0/tracing.py, pyproject.toml, src/charm.py, tests/unit/conftest.py
There are a bunch of tempo tracing related updates:
1. tempo-k8s has been deprecated in favor of tempo ha
2. tracing charm libs need to be fetch-ed from tempo_coordinator_k8s
3. tracing traffic is now relayed through grafana-agent-k8s (like the remaining COS traffic)
2. update tracing charm libs from new repo
Test integration with tempo ha + test relay of traffic through grafana-agent-k8s
Update the postgresql-k8s tracing docs
=> [DPE-5312] Integrate with Tempo HA + test relay support of tracing traffic through grafana-agent-k8s

tests/integration/ha_tests/test_rollback_to_master_label.py, tests/integration/ha_tests/test_upgrade_to_primary_label.py
Re-enable the label upgrade test from `master` to `primary`
Cannot re-enable the roll back test, since the dependency fault charm is local and cannot be upgraded to the specific revision (281)
=> [MISC] Reenable labelling tests

src/grafana_dashboards/postgresql-metrics.json
The previous state of our COS dashboard (the pg one, didn't look at patroni one yet) has some inconsistencies and weirdnesses. This PR aims to fix most of them + renaming of the graphs, so it's clearer what metric they're showcasing.
The diff is very confusing - I'll put comments on the most important changes. Please try it out if you can, LMK your thoughts. Feel free to suggest any more metrics/graphs you would like to see.
=> [DPE-4469] Polish COS dashboard

lib/charms/postgresql_k8s/v0/postgresql.py, src/backups.py, src/charm.py, src/patroni.py, templates/patroni.yml.j2, tests/integration/helpers.py, tests/integration/test_backups.py, tests/integration/test_backups_pitr.py, tests/unit/test_backups.py, tests/unit/test_charm.py
Add timeline management feature. Fixes #612 and fixes #715. [There are the same PR for the VM](https://github.com/canonical/postgresql-operator/pull/629) - basically, it's a port of the same code, so i left description unchanged, bet me know if it can be improved.
I've currently disabled failing unit tests and will fix them after this PR is reviewed.
Main restriction of the [previous PITR work](https://github.com/canonical/postgresql-k8s-operator/pull/554) was lack of the WAL timeline management. Because of this, "move restored cluster to another s3 bucket" blocking message was introduced - to restrict user from having multiple timelines in the single s3 stanza. This PR is a continuation of that work and adds ability to have multiple WAL timelines in the single s3 stanza simultaneously …
=> [DPE-5581] Timeline Management

src/backups.py, src/charm.py, tests/unit/test_backups.py, tests/unit/test_charm.py
[There is the same PR for the VM.](https://github.com/canonical/postgresql-operator/pull/642)
Fixes #591. Fixes #614. Fixes #617. Fixes #713.
I've also implemented model uuid constraint for the S3 stanza according to the DA123.
Overhauls s3 initialization sequence to support leader / primary desync through multiple units.
Introduces the next fields in the app peer data / unit peer data:
* `s3-initialization-start`: the s3 initialization sequence started (only leader) and waiting for it to complete.
* `s3-initialization-block-message`: the s3 initialization error. If it is set, then s3 initialization sequence is interrupted, therefore `s3-initialization-start` and `stanza` are empty. If initialization is ran on desynced primary, it can emerge along with the `s3-initialization-done`.
* …
=> S3 improvements

src/prometheus_alert_rules/patroni_rules.yaml, src/prometheus_alert_rules/pgbouncer_rules.yaml, src/prometheus_alert_rules/postgresql_rules.yaml, tox.ini
Alert rule descriptions do not provide much guidance about what actions the user can take.
Improve the descriptions of the COS alert rule expressions.
The format should be:
1. What happened, or what is the problem
2. What can the user do to recover, or investigate further _(this is the part that's usually missing)_
Here is a good example:
```yaml
summary: PostgresSQL SSL compression active (instance {{ $labels.instance }})
description: |
Database connections have SSL compression enabled. This may add significant jitter in replication delay.
Replicas can turn off SSL compression via `sslcompression=0` in `recovery.conf`.
```
=> [DPE-5658] Update COS alert rules

tests/unit/test_async_replication.py
https://github.com/canonical/postgresql-k8s-operator/issues/739
Improved relations.async_replication module test coverage to ~65
=> [DPE-5662] increase async replication tests coverage

src/backups.py, tests/unit/test_backups.py
See #747. When the `create-backup` action is run on a non-primary unit (the case when TLS is being used), the unit disables the connectivity to the cluster in order to prevent client operations mid-backup. Afterwards, this same unit should re-establish the connectivity. 
Problem: if a switchover happens mid-operation and the replica unit creating the backup becomes the new primary, it will not re-enable connectivity to the cluster due to not being a replica anymore.
Do not check if the unit is the primary or not before re-enabling connectivity (there's no need), but instead checks if it disabled it before -- If so, then enables it back.
=> [DPE-5689] Fix connection rejection rule in `pg_hba.conf`

src/charm.py, tests/unit/test_charm.py
Adds warning and status change before re-initialising to make it more visible in logs
=> [DPE-5712] Add warning logs to Patroni reinitialisation

tests/integration/ha_tests/test_rollback_to_master_label.py
Tweak the label rollback test to download and revert to the revision supporting the old labels
=> [DPE-5693] Reenable label rollback test

src/charm.py, tests/integration/new_relations/test_new_relations.py, tests/unit/test_charm.py
Replica units fail to initialize on Juju 3.6 due to too restrictive permissions rejected by initdb.
> ... FATAL:  data directory "/var/lib/postgresql/data/pgdata" has invalid permissions                                                            
> ... DETAIL:  Permissions should be u=rwx (0700) or u=rwx,g=rx (0750). 
Reducing permissions to the maximum accepted by initdb.
Tech details:
Previously in Juju 3.5, the old Pebble 1.10 [ignored our 0770](https://github.com/canonical/postgresql-k8s-operator/blob/6f10bb97b7d5c591fc4536c9d67afe6cbc27da09/src/charm.py#L906) and set 0750 => everything worked well. 
In Juju 3.6-rc1, the new Pebble 1.16 shipped.
Meanwhile, the Pebble 1.12 [has fixed mkdir](https://github.com/canonical/pebble/releases/tag/v1.12.0).
As a result our 0770 is how set …
=> [DPE-5915] Reduce pgdate permissions

lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py, lib/charms/tempo_coordinator_k8s/v0/tracing.py, tests/integration/new_relations/test_new_relations.py
Indico relation test fails due to the charm blocking over lack of disk space. [E.g.](https://github.com/canonical/postgresql-k8s-operator/actions/runs/11705323476/job/32653406342)
```
INFO     juju.model:model.py:2972 Waiting for model:
database/0 [idle] blocked: <10% free space on pgdata volume.
database/1 [idle] blocked: <10% free space on pgdata volume.
database/2 [idle] blocked: <10% free space on pgdata volume.
```
The underlying issue is likely the host runner running out of disk space.
The PR splits off the client app tests (discourse and indico) in a separate group from the general interface functionality tests and updates the charm libs.
=> [MISC] Split off new interface client app tests

lib/charms/postgresql_k8s/v0/postgresql.py, tests/unit/test_postgresql.py
When rerelating, the charm assumes there are only functions to change ownership of.
Inspect the `prokind` value and use the appropriate alter statement for aggregates, functions and procedures.
Related to #772
=> [DPE-6031] Change owner of functions, procedures and aggregates

templates/patroni.yml.j2, tests/integration/ha_tests/test_rollback_to_master_label.py, tests/integration/ha_tests/test_upgrade_to_primary_label.py
psycopg errors out after upgrade due to `shared_preload_libraries` directive missing in Patroni's `postgresql.parameters` config
* Add shared_preload_libraries` to `postgresql.parameters` config
* Add resources to primary label upgrade tests
=> [DPE-6033] Preload shared libs on normal PG start

src/backups.py, tests/unit/test_backups.py
When trying to restore to the latest time from a repository, the charm complains that a backup ID is required.
Allow users to restore without a backup ID (with only the `--restore-to-time=latest` parameter).
Also, add a new check that prevents the PITR and warns the user that there is no base backup in the latest timeline if there isn't one. Previously, if the user tried to restore from that timeline, the restore would be reported as successful, but in fact, it didn't happen.
=> [DPE-6052] Allow `--restore-to-time=latest` without a `backup-id`

src/backups.py, tests/unit/test_backups.py
This PR removes unnecessary calls to [reload_patroni_configuration](https://github.com/canonical/postgresql-k8s-operator/blob/fdf66d449be185f06586b8ec5a1490d61b507fcd/src/patroni.py#L501-L504) method, in cases where the charm's [update_config](https://github.com/canonical/postgresql-k8s-operator/blob/fdf66d449be185f06586b8ec5a1490d61b507fcd/src/charm.py#L1830-L1909) method is **explicitly called** right before such line. This method already reloads the Patroni configuration internally ([reference](https://github.com/canonical/postgresql-k8s-operator/blob/fdf66d449be185f06586b8ec5a1490d61b507fcd/src/charm.py#L1893)), so it does not make sense to preserve these lines.
---
This discovery was done thanks to the help of @lucasgameiroborges
=> [MISC] Clean-up duplicated Patroni config reloads

config.yaml, lib/charms/postgresql_k8s/v0/postgresql.py, src/charm.py, src/config.py, src/patroni.py, tests/integration/ha_tests/helpers.py, tests/integration/ha_tests/test_synchronous_policy.py, tests/integration/test_config.py, tests/unit/test_charm.py, tests/unit/test_patroni.py
Implements DA135 configuration for synchronous node count.
Adds `all` and  `majority` sync standby policies and ability to set constant number of sync standbys.
=> [DPE-5827] Synchronous node count configuration

.github/workflows/ci.yaml, lib/charms/postgresql_k8s/v0/postgresql.py, lib/charms/postgresql_k8s/v0/postgresql_tls.py, poetry.lock, pyproject.toml, tests/integration/ha_tests/test_rollback_to_master_label.py, tests/integration/ha_tests/test_upgrade_to_primary_label.py
Fix missing certificates in Juju 3.6
=> [MISC] Enable Juju 3.6

src/backups.py, src/charm.py, src/config.py, src/patroni.py, src/relations/async_replication.py, src/relations/db.py, tests/integration/ha_tests/helpers.py, tests/integration/ha_tests/test_async_replication.py, tests/integration/helpers.py, tests/integration/new_relations/helpers.py, tests/integration/test_backups.py, tests/integration/test_backups_pitr.py
This PR updates the typing signatures to leverage Python 3.10+ syntax.
It is an effort to harmonize typing syntax within the project, as there are some discrepancies regarding how some of it is used throughout the files (i.e. see `Optional` usages [here](https://github.com/search?q=repo%3Acanonical%2Fpostgresql-k8s-operator+path%3A%2F%5Esrc%5C%2F%2F+%22Optional%22&type=code), and `<type> | None` usages [here](https://github.com/search?q=repo%3Acanonical%2Fpostgresql-k8s-operator+path%3A%2F%5Esrc%5C%2F%2F+%22%7C+None%22&type=code)).
In short:
```diff
- Dict[<type>, <type>]
+ dict[<type>, <type>]
- List[<type>]
+ list[<type>]
- Set[<type>]
+ set[<type>]
- Tuple[<type>]
+ tuple[<type>]
- Optional[<type>]
+ <type> | None
```
- I have not updated the syntax on the postgresql-k8s [charm …
=> [MISC] Migrate typing syntax to Python 3.10+

lib/charms/postgresql_k8s/v0/postgresql.py
Missed typing incompatibility with py 3.8 (Focal)
=> [MISC] Focal lib changes

src/backups.py, src/charm.py, src/relations/async_replication.py, src/relations/db.py, src/relations/postgresql_provider.py, tests/unit/test_charm.py
This PR defines a set of charm properties to reduce the chance of introducing typos when checking for specific keys in the app / unit data-bags, as well as reduce the cognitive load of logical statements.
The **new** properties are:
- `is_cluster_restoring_backup`.
- `is_cluster_restoring_to_time`.
- `is_unit_departing`
- `is_unit_stopped`.
The **existing** properties, now used throughout the codebase are:
- `is_cluster_initialised`.
=> [MISC] Define charm utility properties

charmcraft.yaml, scripts/__init__.py, scripts/rotate_logs.py, src/backups.py, tests/unit/test_rotate_logs.py, tox.ini
This PR ports part of the changes introduced in [this PR](https://github.com/canonical/postgresql-operator/pull/729) VM counter-part, by creating a folder `scripts` folder, and moving there the `rotate_logs.py` script. This change is proposed in preparation for the addition of a new LDAP-Sync pebble service stand-along script, which does not belong alongside the rest of the `src` logic.
Please review the [couple of instances](https://github.com/search?q=repo%3Acanonical%2Fpostgresql-k8s-operator%20%22%2Fhome%2Fpostgres%2Frotate_logs.py%22&type=code) where the script is referenced within `/home/postgres` folder. Not sure if my proposed changes affect that.
=> [MISC] Split topology script

lib/charms/postgresql_k8s/v0/postgresql.py, src/charm.py, src/constants.py, tests/integration/helpers.py, tests/integration/new_relations/test_new_relations_1.py, tests/integration/new_relations/test_relations_coherence.py, tests/unit/test_postgresql.py
This PR moves certain string into constant values, so that they could be referenced throughout the codebase.
These two in particular (i.e. the `admin` permission group and the `postgres` default database name) will be used in the upcoming LDAP support. These changes are proposed an isolation, as they have nothing to do with the LDAP support itself.
=> [MISC] Define charm constants

src/backups.py, tests/unit/test_backups.py
Handle potential exception
Port of https://github.com/canonical/postgresql-operator/pull/727
=> [DPE-6323] Handle missing stanza output

lib/charms/postgresql_k8s/v0/postgresql.py, src/charm.py, src/relations/postgresql_provider.py, tests/unit/test_postgresql_provider.py
This PR contains a slight refactor to make code more compatible with the upcoming LDAP integration.
In that effort, we would need to sanitise the list of `extra-user-roles` a Juju cluster administrator could provide via the data-integrator [charm](https://github.com/canonical/data-integrator), so that none of the upcoming _access groups_ (see [spec](https://docs.google.com/document/d/1Wt9VhdYCVzPh6qfwYiKOcfQwQ6UW6765S09dFjnuBXY/edit?tab=t.0) for context) is provided as a security by-pass. With that in mind, some centralised place to perform this sanitisation is required, and such operation is easier to carry on considering the list of roles as a `list`, instead of a comma-separated `str`.
=> [MISC] Sanitize PostgreSQL extra-user-roles arg

lib/charms/postgresql_k8s/v0/postgresql.py
This PR fixes PR https://github.com/canonical/postgresql-k8s-operator/pull/876 by making the PostgreSQL charm lib compatible with Python 3.8 (required by PGBouncer VM).
Apologies for the noise 😞
=> [MISC] Fix PostgreSQL lib function signature

lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py, tests/integration/conftest.py, tests/integration/test_backups_aws.py, tests/integration/test_backups_gcp.py, tests/integration/test_backups_pitr_aws.py, tests/integration/test_backups_pitr_gcp.py
Forked PRs have no access to Github secrets, so cloud backup tests will always fail.
* Update charm libs
* Split the cloud config fixture
* Skip backup tests if no credentials are provided
Tested on https://github.com/canonical/postgresql-k8s-operator/pull/885
=> [MISC] Skip backup tests without creds

config.yaml, src/charm.py, src/config.py
The `wal_keep_size` PostgreSQL parameter is not configurable through the charm.
Add that parameter as a config option.
It needs to be set through Patroni dynamic configuration as per https://patroni.readthedocs.io/en/latest/patroni_configuration.html.
=> [DPE-6675] Add wal_keep_size config option

lib/charms/postgresql_k8s/v0/postgresql.py, src/charm.py, src/relations/db.py, src/relations/postgresql_provider.py, src/upgrade.py, tests/unit/test_db.py, tests/unit/test_postgresql.py, tests/unit/test_postgresql_provider.py
This is the 1st PR to introduce LDAP support into PostgreSQL. The complete list of changes can be seen in [this branch](https://github.com/canonical/postgresql-k8s-operator/tree/sinclert/ldap-integration-all).
This PR defines three different _access groups_, in order to differentiate authentication methods within the `pg_hba.conf` file when LDAP is activated (i.e. the GLAuth charm related). These _access groups_ are not yet put into such file, but they are leveraged in order to:
- Assign any charm internal user to the _internal-access_ group.
- Assign any charm relation user to the _relation-access_ group.
- PostgreSQL-LDAP [specification](https://docs.google.com/document/d/1Wt9VhdYCVzPh6qfwYiKOcfQwQ6UW6765S09dFjnuBXY/edit?tab=t.0).
=> [DPE-6344] LDAP I: Create access groups

lib/charms/certificate_transfer_interface/v0/certificate_transfer.py, lib/charms/glauth_k8s/v0/ldap.py, lib/charms/postgresql_k8s/v0/postgresql_tls.py, metadata.yaml, pyproject.toml, src/charm.py, tests/integration/helpers.py, tests/integration/test_backups_pitr_aws.py, tests/integration/test_backups_pitr_gcp.py, tests/integration/test_tls.py, tests/unit/test_charm.py, tests/unit/test_postgresql_tls.py
This is the 2nd PR to introduce LDAP support into PostgreSQL. The complete list of changes can be seen in [this branch](https://github.com/canonical/postgresql-k8s-operator/tree/sinclert/ldap-integration-all).
This PR introduces the `ldap` V0 charm library, as well as the `certificate-transfer` V0 charm library. Despite having V1 of the latter already published, V0 requires `jsonschema` instead of `pydantic` which plays nicely with the version of the TLS charm lib we are using (see [code](https://github.com/canonical/postgresql-k8s-operator/blob/e1684df29ffb8fdc7a80e19847daab83e27cdf5b/lib/charms/tls_certificates_interface/v2/tls_certificates.py#L312)). I would say whenever we bump one, we bump the other.
- PostgreSQL-LDAP [specification](https://docs.google.com/document/d/1Wt9VhdYCVzPh6qf …
=> [DPE-6344] LDAP II: Include charm libs

config.yaml, src/charm.py, src/config.py, src/ldap.py, src/patroni.py, templates/patroni.yml.j2, tests/integration/test_ldap.py, tests/spread/test_ldap/task.yaml, tests/unit/test_charm.py, tests/unit/test_ldap.py, tests/unit/test_patroni.py
This is the 3rd PR to introduce LDAP support into PostgreSQL. The complete list of changes can be seen in [this branch](https://github.com/canonical/postgresql-k8s-operator/tree/sinclert/ldap-integration-all).
This PR extends the charm configuration to include all the initially proposed configuration options, which are useful for local debugging (some of them will go away before marking the integration complete). In addition, it creates the [PostgreSQLLDAP](https://github.com/canonical/postgresql-k8s-operator/blob/ldap-integration/handler-methods/src/ldap.py) class to hold all the GLAuth related handlers, similar to how other classes within the charm hold all the handlers for a particular functionality (i.e. `PostgreSQLBackups`, `PostgreSQLUpgrades`, etc).
- PostgreSQL-LDAP …
=> [DPE-6344] LDAP III: Define config and handlers

src/backups.py, src/charm.py, src/relations/async_replication.py, tests/unit/test_charm.py
This is the 4th PR to introduce LDAP support into PostgreSQL. The complete list of changes can be seen in [this branch](https://github.com/canonical/postgresql-k8s-operator/tree/sinclert/ldap-integration-all).
This PR leverages the upcoming `ldap-sync` snap service in order to start the synchronization of LDAP users whenever the PostgreSQL-K8s charm relates to the GLAuth-K8s one. Given that the service has not yet defined within the snap, the method depending on such service existing has been temporarily disabled.
- PostgreSQL-LDAP [specification](https://docs.google.com/document/d/1Wt9VhdYCVzPh6qfwYiKOcfQwQ6UW6765S09dFjnuBXY/edit?tab=t.0).
---
Depends on PR https://github.com/canonical/charmed-postgresql-snap/pull/88.
=> [DPE-6344] LDAP IV: Define pebble service

config.yaml, lib/charms/postgresql_k8s/v0/postgresql.py, src/charm.py, src/config.py, tests/unit/test_charm.py, tests/unit/test_postgresql.py
This is the 5th PR to introduce LDAP support into PostgreSQL. The complete list of changes can be seen in [this branch](https://github.com/canonical/postgresql-k8s-operator/tree/sinclert/ldap-integration-all).
This PR introduces the last configuration option for the integration: `ldap_map`. This configuration option will be used to specify a mapping between LDAP users coming from specific LDAP groups, to pre-created PostgreSQL authorization groups, so they can actually connect / query the database. The syntax has been copied from Percona's MySQL ([reference](https://docs.percona.com/percona-server/8.0/ldap-simple-variables.html#authentication_ldap_simple_group_role_mapping)).
- PostgreSQL-LDAP [specification](https://docs.google.com/document/d/1Wt9VhdYCVzPh6qfwYiKOcfQwQ6UW6765S09dFjnuBXY/e …
=> [DPE-6344] LDAP V: Define mapping option

config.yaml, lib/charms/postgresql_k8s/v0/postgresql.py, src/backups.py, src/charm.py, src/config.py, src/relations/async_replication.py, tests/unit/test_charm.py, tests/unit/test_postgresql.py
Syncing main to 16/edge:
* LDAP integration
=> [MISC] Sync main to 16/edge

lib/charms/postgresql_k8s/v0/postgresql.py
This PR fixes a subtle crash where the PostgreSQL charm lib could not establish the connection when listing groups / users, causing an `UnboundLocalError` error (see failing [CI job](https://github.com/canonical/postgresql-operator/actions/runs/14311792544/job/40234376532))
The correct handling of this _connection failure_ is something that the PostgreSQL-VM operation relies on, as it was not experienced when developing the LDAP integration for the PostgreSQL-K8s one.
=> [MISC] Add missing connection vars

src/charm.py, src/ldap.py, tests/unit/test_ldap.py
This PR removes the `ca_transferred` property from the PostgreSQLLDAP class, so that relationship could be established cross-model, which is not possible at the moment. This change harmonizes the logic with respect to its PostgreSQL-VM operator equivalent.
- Fixes a typo related to how the pebble service is called, when it needs to be stopped.
=> [DPE-6344] Remove CA transferred check

src/charm.py, src/ldap.py, src/relations/postgresql_provider.py, tests/integration/ha_tests/test_upgrade.py, tests/integration/ha_tests/test_upgrade_from_stable.py, tests/integration/helpers.py, tests/unit/test_ldap.py, tests/unit/test_postgresql_provider.py
Sync main into 16/edge:
* LDAP fixes
=> [MISC] Sync main into 16/edge

src/charm.py, tests/unit/test_charm.py
Make username parameter mandatory for `set-password` action
=> [DPE-6664] Make username mandatory in set-password

lib/charms/postgresql_k8s/v0/postgresql_tls.py, src/charm.py
This PR solves a bug when, upon having a PostgreSQL-K8s charm properly connected to a GLAuth charm (see [this guide](https://charmhub.io/postgresql-k8s/docs/h-enable-ldap)), any refresh to the operator revision will not persist the already transferred certificates to the new unit.
- This should not be happening on PostgreSQL-VM, as the file-system there is stable between refreshes.
- The `push_tls_files_to_workload` method signature has been harmonized with respect to its siblings (see https://github.com/canonical/postgresql-k8s-operator/commit/e21a6a6d9d0f27f409bc33adc3d8b67d5e4d739a).
=> [DPE-6344] Persist transferred certificates upon start

lib/charms/postgresql_k8s/v0/postgresql.py, tests/unit/test_postgresql.py
This PR extends the relation-user listing SQL syntax in order to account for name prefix discrepancies between K8s & VM. Ideally, we would follow the same syntax in both substrates, but I understand a migration attempt may be painful.
The discrepancy can be seen in the following files:
- `src/relations/db.py`: PostgreSQL K8s [snippet](https://github.com/canonical/postgresql-k8s-operator/blob/083b3036c243b8d53289028a5a4cd46a6b069947/src/relations/db.py#L175), PostgreSQL VM [snippet](https://github.com/canonical/postgresql-operator/blob/573517b6274a6f013ef2228ee2d0759612eee4d5/src/relations/db.py#L174).
- `src/relations/provider.py`: PostgreSQL K8s [snippet](https://github.com/canonical/postgresql-k8s-operator/blob/083b3036c243b8d53289028a5a4cd46a6b069947/src/relations/postgresql_provider.py …
=> [MISC] Extend relation-user listing syntax

docs/redirects.txt
Redirects configured in `redirects.txt` do not take effect when built on on RTD, despite a successful build with no errors.
I believe this has to do with how either RTD or the Sphinx builder recognizes files in the HTML output. Since the source paths did not have a forward slash, it did not generate `index.html` files for them.
Added a forward slash to all source paths.
=> fix: add forward slash to source paths

templates/pgbackrest.logrotate.j2
Backport from https://github.com/canonical/postgresql-operator/pull/939 to PG16 K8s.
The pgBackRest activity (backup creation, stanza initialisation, etc) could take minutes, as a result every minute logs rotation could move the current log A.log to A.log_$date.log and will be moved further as logrorate rule operates all *.log files in the folder:
> /var/snap/charmed-postgresql/common/var/log/pgbackrest/*.log { ...
It results in:
-rw------- 1 postgres postgres     0 Feb 18 09:25 all-server.log
-rw------- 1 postgres postgres     0 Feb 18 09:19 all-server.log-20250218_09:18.log
-rw------- 1 postgres postgres     0 Feb 18 09:20 all-server.log-20250218_09:18.log-20250218_09:19.log
-rw------- 1 postgres postgres     0 Feb 18 09:21 all-server.log-20250218_09:18.log-20250218_09:19.log-20250218_09 …
=> DPE-6662 Fix pgbackrest logs names on logs rotation

lib/charms/postgresql_k8s/v0/postgresql.py, src/relations/postgresql_provider.py, tests/unit/test_postgresql_provider.py
Port of https://github.com/canonical/postgresql-operator/pull/959 from VM
Hold the database requested hook instead of relying on relation changed events
=> [MISC] Hold database created hook for pg_hba changes

docs/explanation/legacy-charm.md
New RTD builds fail due to a typo in a reference to an internal page.
As a result, redirects are not being correctly applied to PostgreSQL K8s documentation because the last successful build was before the redirect files and dependencies were added.
Fixed typo.
=> fix: internal reference typo

src/backups.py, templates/pgbackrest.conf.j2, tests/unit/test_backups.py
Backport of https://github.com/canonical/postgresql-operator/pull/983:
* Change the default compression algorithm
* Increase processes when restoring backup
=> [DPE-7549] Add compression and restore max-process

src/patroni.py, src/upgrade.py, tests/integration/ha_tests/helpers.py, tests/integration/ha_tests/test_upgrade_from_stable.py, tests/integration/new_relations/test_new_relations_2.py, tests/unit/test_patroni.py
Relates to https://github.com/canonical/postgresql-k8s-operator/issues/669
Failsafe mode is not enabled on upgraded deployments: https://github.com/canonical/postgresql-k8s-operator/issues/669#issuecomment-3163328798
* Patch failsafe mode during upgrade
* Disable discourse test, persistently failning
=> [DPE-5311] Patch failsafe mode on upgrade

src/patroni.py, templates/patroni.yml.j2, tests/integration/test_config.py, tests/unit/test_patroni.py
Charmed PG16 has migrated to scram-sha-256 by default, but there are still md5 leftovers.
Insist on scram-sha-256 in Patroni config unless user configured to use md5 in charm config.
Keep pgbouncer_auth_relation_% users in md5.
=> DPE-6901 Replace md5 with scram-sha-256 in patroni/pg_hba.conf

metadata.yaml
This PR updates the `metadata.yaml` for PostgreSQL 16 releases on Charmhub in order to version the home page with the docs.
It addresses issue https://github.com/canonical/postgresql-operator/issues/1082
* Replaced `docs:` link with new RTD docs - this [new Charmhub feature](https://github.com/canonical/charmhub.io/pull/2159) will create a dedicated button in the sidebar.
* Updated `summary:` and `description:` keys, since they will be the new title and content of the Charmhub home page.
* Removed old broken link to `chat.charmhub.io`
=> Update Charmhub home page (16)
